### ISSUE TITLE
Dark theme

### ISSUE THREAD

**Issue by sanyavertolet** [m-danya/prolog-testing-system#6]
Suggestion to add theme selection as far as light theme might be hard to use sometimes.

**Comment by m-danya** [comment]
Выглядит [несложно](https://mui.com/material-ui/customization/dark-mode/), надо обернуть компонент `<App />` в `ThemeProvider`. Пулл реквесты приветствуются :)

**Comment by sanyavertolet** [comment]
@m-danya Заассайнишь на меня?
Сделаю после матлога

**Comment by m-danya** [comment]
Отлично)
