### ISSUE TITLE
Improve mobile version

### ISSUE THREAD

**Issue by m-danya** [m-danya/prolog-testing-system#8]
Надо обернуть 3 подряд идущих кнопки в правой части сайта в Stack или Grid с xs=.. и lg=.. (google: Material UI Stack React), чтобы на мобильном они располагались друг под другом. А то сейчас текст на них съезжает.

**Comment by m-danya** [comment]
Ещё надо выровнять в мобильной версии кнопки смены темы и "о проекте" по правому краю (через `justify-items` какой-нибудь)

**Comment by sanyavertolet** [comment]
С мобильной версии не работает загрузка файла, нужно прятать кнопку на мобилках

**Comment by m-danya** [comment]
У меня работает на Android

**Comment by sanyavertolet** [comment]
> У меня работает на Android

У меня на Android 13 не работает через Chrome
